name: Build ISO
on:
  push:
  workflow_dispatch:
  schedule:
   - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Set up Arch environment
      run: |
        pacman --noconfirm -Sy archlinux-keyring
        pacman --noconfirm -Su archiso openssh
    - name: Build ISO
      id: build
      run: |
        ./build.sh -v
        echo "::set-output name=image_file::$(pwd)/$(ls out/*.iso)"
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v3
      with:
        name: cactus.iso
        path: ${{ steps.build.outputs.image_file }}
    - name: Upload to file server
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_DESTINATION: ${{ secrets.SSH_DESTINATION }}
        INPUT: ${{ steps.build.outputs.image_file }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan $SSH_HOST > ~/.ssh/known_hosts
        echo $SSH_KEY > ~/.ssh/transfer_key
        scp -i ~/.ssh/transfer_key -o StrictHostKeyChecking=no $INPUT $SSH_USER@$SSH_HOST:$SSH_DESTINATION
