name: Build ISO
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Set up Arch environment
      run: |
        pacman --noconfirm -Sy archlinux-keyring
        pacman --noconfirm -Su archiso
    - name: Build ISO
      id: build
      run: |
        ./build.sh -v
        "::set-output name=image_file::$(pwd)/$(ls out/*.iso)"
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v3
      with:
        name: cactus.iso
        path: ${{ steps.build.outputs.image_file }}
